###
# GET all recipes
GET https://orecipesapi.onrender.com/api/recipes
###


### 
# Check credentials
POST https://orecipesapi.onrender.com/api/login
content-type: application/json

{
  "email": "bob@mail.io",
  "password": "bobo"
}
###


# ### 
# # UPDATE card
# PATCH http://localhost:5000/cards/2
# content-type: application/json

# {
#     "content": "carte modifiée 5",
#     "position": 3,
#     "list_id": 1
# }
# ###


# ###
# # DELETE card
# DELETE http://localhost:5000/cards/1
# ###


# ###
# # ADD Tag to card
# PUT http://localhost:5000/cards/1/tags/2
# ###

# ###
# # REMOVE Tag from card
# DELETE http://localhost:5000/cards/1/tags/2
# ###
